spring:
  redis:
    host: 47.94.202.15
    port: 6379
    password: myredis123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 2
    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dangdb
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  main:
    banner-mode: off
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    use-generated-keys: true
  global-config:
    banner: off
  mapper-locations: ./com/ac/dang_dang/mapper/*.xml
file:
  upload:
    path: E:\IdeaProjects\dang_dang\src\main\resources\static\img\upload